-- Cria schema "recursos_humanos"
CREATE SCHEMA IF NOT EXISTS RECURSOS_HUMANOS;

-- acessar o schema criado para criar as tables
USE RECURSOS_HUMANOS;

-- Cria a tabela "colaboradores"
CREATE TABLE COLABORADORES (
    NOME VARCHAR(15) NOT NULL,
    SOBRENOME VARCHAR(15) NOT NULL,
    CPF CHAR(11) NOT NULL,
    DATANASCIMENTO DATE,
    ENDERECO VARCHAR(30),
    GENERO CHAR(1),
    SALARIO DECIMAL(7, 2 ),
    PIS CHAR(11),
    DNO INT NOT NULL,
    CONSTRAINT PK_COLAB PRIMARY KEY (CPF)
);

-- Altera a coluna Dno e coloca o default 1.
ALTER TABLE COLABORADORES MODIFY DNO INT NOT NULL DEFAULT 1;

-- Descreve a estrutura da tabela
DESCRIBE colaboradores;

-- -- Cria outra tabela para o database "departamento"
CREATE TABLE DEPARTAMENTO (
    NOMEDEPARTAMENTO VARCHAR(15) NOT NULL,
    NUMERODEPARTAMENTO INT NOT NULL,
    CPFGERENTE CHAR(11),
    GERENTEADMISSAO DATE,
    DATACRIACAODEPTO DATE,
    CONSTRAINT CHECA_CRIACAO_DEPTO CHECK (DATACRIACAODEPTO < GERENTEADMISSAO),
    CONSTRAINT PK_DEPTO PRIMARY KEY (NUMERODEPARTAMENTO),
    CONSTRAINT NOME_UNICO_DEPTO UNIQUE (NOMEDEPARTAMENTO),
    FOREIGN KEY (CPFGERENTE) REFERENCES COLABORADORES (CPF)
);

-- Adiciona foreign key em departamento
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPTO FOREIGN KEY(CPFGERENTE) REFERENCES COLABORADORES(CPF) ON UPDATE CASCADE;

-- Descreve a tabela departamento
DESCRIBE departamento;

SELECT * FROM LOCALIZACAO_DEPTOS;



-- Cria tabela localizacao_deptos
CREATE TABLE LOCALIZACAO_DEPTOS (
    NUMERODEPARTAMENTO INT NOT NULL,
    LOCALIZACAODEPARTMENTO VARCHAR(15) NOT NULL,
    CONSTRAINT PK_DEPT_LOCAL PRIMARY KEY (NUMERODEPARTAMENTO, LOCALIZACAODEPARTMENTO),
    CONSTRAINT FK_DEPT_LOC FOREIGN KEY (NUMERODEPARTAMENTO) REFERENCES DEPARTAMENTO (NUMERODEPARTAMENTO)
);

-- Alterando o nome da coluna
ALTER TABLE LOCALIZACAO_DEPTOS RENAME COLUMN LOCALIZACAODEPARTMENTO TO LOCALIZACAODEPARTAMENTO;

-- Cria a tabela projetos
CREATE TABLE PROJETOS (
    NOMEPROJETO VARCHAR(15) NOT NULL,
    NUMEROPROJETO INT NOT NULL,
    LOCALPROJETO VARCHAR(15),
    NUMERODEPARTAMENTO INT NOT NULL,
    PRIMARY KEY (NUMEROPROJETO),
    CONSTRAINT PROJETOUNICO UNIQUE (NOMEPROJETO),
    CONSTRAINT FK_PROJETO FOREIGN KEY (NUMERODEPARTAMENTO) REFERENCES DEPARTAMENTO (NUMERODEPARTAMENTO)
);

-- Cria tabela alocacao
CREATE TABLE ALOCACAO (
    CPFCOLABORADOR CHAR(11) NOT NULL,
    NUMEROPROJETO INT NOT NULL,
    HORAS DECIMAL(3, 1 ) NOT NULL,
    PRIMARY KEY (CPFCOLABORADOR, NUMEROPROJETO),
    CONSTRAINT FK_ALOC_COLAB FOREIGN KEY (CPFCOLABORADOR) REFERENCES COLABORADORES (CPF)
    
);
--- FALTA INSERIR OS DADOS AQUI ----
-- Cria a tabela dependentes
SELECT * FROM DEPENDENTES;

CREATE TABLE DEPENDENTES (
    CPFCOLABORADOR CHAR(11) NOT NULL,
    NOMEDEPENDENTE VARCHAR(45) NOT NULL,
    GENERO CHAR(1),
    DATANASCIMENTO DATE,
    PARENTESCO VARCHAR(8),
    PRIMARY KEY (CPFCOLABORADOR, NOMEDEPENDENTE),
    CONSTRAINT FK_DEPENDENTE FOREIGN KEY (CPFCOLABORADOR) REFERENCES COLABORADORES (CPF)
);

-- Mostra todas as tabelas do schema recursos_humanos
SHOW TABLES;
DESC DEPENDENTES;

-- Mostra todas as constraints do schema
SELECT
    *
FROM
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE
    CONSTRAINT_SCHEMA = 'recursos_humanos';

DESC DEPENDENTES;